on:
  pull_request:
    paths:
      - 'packages/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Try native
    steps:
      - name: Test Step
        run: echo "It works"

  required:
    runs-on: ubuntu-latest
    name: Required
    steps:
      - name: Test Step
        run: echo "It works"

  required-matrix:
    runs-on: ubuntu-latest
    name: Required ${{ matrix.suite }}
    strategy:
      matrix:
        suite:
          - new
          - old
    steps:
      - name: Test Step
        run: echo "It works"