on:
  pull_request:
    paths:
      - 'website/**' # Need to be kept in sync manually
      - 'dependent/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Required # Name that needs to Match
    steps:
      - name: Test Step
        run: echo "It works"